// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1raBMLzM3B7WXiUxkXjQknm_NOy7hGfk',
    appId: '1:342333477118:web:0b567c5e4d2dec373795af',
    messagingSenderId: '342333477118',
    projectId: 'test-project-be4d6',
    authDomain: 'test-project-be4d6.firebaseapp.com',
    storageBucket: 'test-project-be4d6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdSF08Sw-QRV10_MwqE1IUZGt9QvJ8RMI',
    appId: '1:342333477118:android:9bb809a5ac3e6f7c3795af',
    messagingSenderId: '342333477118',
    projectId: 'test-project-be4d6',
    storageBucket: 'test-project-be4d6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAI-ynhfpVbDFEY5bCUf3KoCHiCNs13Si0',
    appId: '1:342333477118:ios:1f7d6d4b18f1c2a13795af',
    messagingSenderId: '342333477118',
    projectId: 'test-project-be4d6',
    storageBucket: 'test-project-be4d6.appspot.com',
    iosClientId: '342333477118-i3igm6788sic394fhdo81q1kv7q1ka5u.apps.googleusercontent.com',
    iosBundleId: 'com.eventora.eventora',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAI-ynhfpVbDFEY5bCUf3KoCHiCNs13Si0',
    appId: '1:342333477118:ios:1f7d6d4b18f1c2a13795af',
    messagingSenderId: '342333477118',
    projectId: 'test-project-be4d6',
    storageBucket: 'test-project-be4d6.appspot.com',
    iosClientId: '342333477118-i3igm6788sic394fhdo81q1kv7q1ka5u.apps.googleusercontent.com',
    iosBundleId: 'com.eventora.eventora',
  );
}
